### PR TITLE
Bug fixes and Function additions

### PR DESCRIPTION
**Pull request by YoshikiIto-abc**
BugFix Issues #4
BugFix Issues #5
Added "reception setting" "transmission setting" "setting" "log" item to Windows firewall setting
Added "description" "User must change password at next login" item  to Windows user setting

### CODE REVIEW

**Comment by YoshikiIto-abc** [comment]
We will also attach Excel2YAML which corresponds to this modification.
[Excel2YAML_1.0.0.zip](https://github.com/SHIFT-ware/shift_ware/files/1726374/Excel2YAML_1.0.0.zip)

**Comment by YoshikiIto-abc** [comment]
I will also attach explanatory materials for additional functions
[Explanation_of_function_addition.zip](https://github.com/SHIFT-ware/shift_ware/files/1726402/Explanation_of_function_addition.zip)

**Comment by YoshikiIto-abc** [comment]
Attach test results for additional functions
[Additional_function_test_results.zip](https://github.com/SHIFT-ware/shift_ware/files/1726761/Additional_function_test_results.zip)

**Review by zanashiruamaru — APPROVED** [review]
GJ

**Pull request closed without merging**
